export { IStack, IScopedStack, IStackDictionary, IScopedStackDictionary } from './IDataStructures'
export { Stack } from './src/Stack'
export { ScopedStack } from './src/ScopedStack'
export { StackDictionary } from './src/StackDictionary'
export { ScopedStackDictionary } from './src/ScopedStackDictionary'